pipeline {
    agent any

    environment {
        IMAGE_NAME = "shubhamkadaskar/web-app"
        IMAGE_TAG = "1.0"
        KUBE_DEPLOYMENT = "springboot-deployment.yaml"
        KUBE_SERVICE = "springboot-service.yaml"
    }

    stages {
    stage('Checkout') {
        steps {
            git branch: 'main', url: 'https://github.com/buildwithshubham/WebProject.git'
        }
    }

        stage('Build') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }

        stage('Docker Build') {
            steps {
                sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ."
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([string(credentialsId: 'dockerhub-token', variable: 'DOCKER_TOKEN')]) {
                    sh "echo $DOCKER_TOKEN | docker login -u shubhamkadaskar --password-stdin"
                    sh "docker push ${IMAGE_NAME}:${IMAGE_TAG}"
                }
            }
        }

        stage('Deploy to Minikube') {
            steps {
                sh "kubectl apply -f ${KUBE_DEPLOYMENT}"
                sh "kubectl apply -f ${KUBE_SERVICE}"
            }
        }
    }
}
