pipeline {
    agent any

    environment {
        IMAGE_NAME = "shubhamkadaskar/web-app"
        IMAGE_TAG = "1.0"
        KUBE_DEPLOYMENT = "springboot-deployment.yaml"
        KUBE_SERVICE = "springboot-service.yaml"
        CLUSTER_NAME = "my-autopilot-cluster"
        REGION = "asia-south1"
        PROJECT_ID = "midyear-calling-472010-p3"  // <-- Replace with your actual GCP project ID
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'dev', url: 'https://github.com/buildwithshubham/WebProject.git'
            }
        }

        stage('Build') {
            steps {
                dir('web') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('web') {
                    sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ."
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([string(credentialsId: 'dockerhub-token', variable: 'DOCKER_TOKEN')]) {
                    sh '''
                        echo "$DOCKER_TOKEN" | docker login -u shubhamkadaskar --password-stdin
                        docker push ${IMAGE_NAME}:${IMAGE_TAG}
                    '''
                }
            }
        }

        stage('Authenticate to GCP') {
            steps {
                withCredentials([file(credentialsId: 'gcp-sa-key', variable: 'GOOGLE_APPLICATION_CREDENTIALS')]) {
                    sh '''
                        echo "Activating GCP service account..."
                        gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
                        gcloud config set project ${PROJECT_ID}
                        gcloud container clusters get-credentials ${CLUSTER_NAME} --region=${REGION}
                    '''
                }
            }
        }

        stage('Deploy to GKE') {
            steps {
				 dir('web') {
         	     echo "Deploying application to GKE..."
         	     sh "kubectl apply -f ${KUBE_DEPLOYMENT}"
           		 sh "kubectl apply -f ${KUBE_SERVICE}"
           		 sh "kubectl apply -f springboot-podmonitor.yaml || true"
              }
            }
        }
    }
}
