apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: springboot-app-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: springboot
  namespaceSelector:
    any: true
  podMetricsEndpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
